# Generated by Django 5.0.5 on 2024-05-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['brand', 'model'], 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='deviceassignment',
            options={'ordering': ['-assigned_at'], 'verbose_name': 'Device Assignment', 'verbose_name_plural': 'Device Assignments'},
        ),
        migrations.AlterModelOptions(
            name='deviceconditionlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Device Condition Log', 'verbose_name_plural': 'Device Condition Logs'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
        migrations.AlterModelTable(
            name='device',
            table='device',
        ),
        migrations.AlterModelTable(
            name='deviceassignment',
            table='device_assignment',
        ),
        migrations.AlterModelTable(
            name='deviceconditionlog',
            table='device_condition_log',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
